/**	SortationCommandType (分拣操作命令类型)	*/
export enum SortationCommandType {
  /**	X轴反向移动(H-->A)	*/ MoveXNegative = 'MoveXNegative',
  /**	X轴正向移动(A-->H)	*/ MoveXPostive = 'MoveXPostive',
  /**	Y轴正向移动(1-->8)	*/ MoveYPostive = 'MoveYPostive',
  /**	Y轴反向移动(8-->1)	*/ MoveYNegative = 'MoveYNegative',
  /**	停止移动	*/ Stop = 'Stop',
  /**	抓手上升	*/ TongUp = 'TongUp',
  /**	抓手下降	*/ TongDown = 'TongDown',
  /**	抓手合	*/ TongClose = 'TongClose',
  /**	抓手开	*/ TongOpen = 'TongOpen',
  /**	抓手旋转	*/ TongRotate = 'TongRotate',
  /**	抓手旋转复位	*/ TongRotateRST = 'TongRotateRST',
  /**	设置原点	*/ SetRSTPosition = 'SetRSTPosition',
  /**	设置G2中心点位置	*/ SetG2Position = 'SetG2Position',
  /**	设置B7中心点位置	*/ SetB7Position = 'SetB7Position',
  /**	设置投掷点位置	*/ SetDropPosition = 'SetDropPosition',
  /**	设置预备点位置	*/ SetReadyPosition = 'SetReadyPosition',
  /**	操作台开	*/ ConsoleOpen = 'ConsoleOpen',
  /**	操作台关	*/ ConsoleClose = 'ConsoleClose',
  /**	手动开湿垃圾门	*/ DropPortOpen = 'DropPortOpen',
  /**	手动关湿垃圾门	*/ DropPortClose = 'DropPortClose',
  /**	是否需要旋转抓取旋转消息	*/ GradRotate = 'GradRotate',
  /**	分拣结束消息	*/ Finished = 'Finished',
  /**	手动测试开始	*/ BeginTest = 'BeginTest',
  /**	手动测试结束	*/ EndTest = 'EndTest',
  /**	指定点位抓取物品  A1-H8	*/ Grab = 'Grab',
}
